[programs.devnet]
skill_stake = "C3e8kFFYMsEKxXwjMXix3vKSLfk9WwS1xcHeg5gedjvV"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"

[toolchain]
anchor_version = "0.30.1"
